import Config

dev_port = String.to_integer(System.get_env("PORT") || "4000")

# Let manual QA run against a separate durable database and local port without
# ever switching the primary development server away from its default database.
dev_database = System.get_env("STORYTELLER_DB_NAME") || "storyteller_dev"

# Configure your database
config :storyteller, Storyteller.Repo,
  username: System.get_env("STORYTELLER_DB_USERNAME", System.get_env("USER", "root")),
  password: System.get_env("STORYTELLER_DB_PASSWORD"),
  socket_dir: System.get_env("STORYTELLER_DB_SOCKET_DIR", "/var/run/postgresql"),
  database: dev_database,
  stacktrace: true,
  show_sensitive_data_on_connection_error: false,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :storyteller, StorytellerWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: dev_port],
  check_origin: ["http://127.0.0.1:#{dev_port}", "http://localhost:#{dev_port}"],
  code_reloader: true,
  debug_errors: true,
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:storyteller, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:storyteller, ~w(--watch)]}
  ]

config :storyteller, Storyteller.Auth.OAuth,
  callback_uri: "http://127.0.0.1:#{dev_port}/auth/callback"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :storyteller, StorytellerWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/storyteller_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :storyteller, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Phoenix debug logs include LiveView event and session parameters. Keep player
# text and session values out of the local console while retaining safe info logs.
config :logger, level: :info

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
